{% set version = "1.3.1" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-beanplot
  version: {{ version|replace("-", "_") }}

source:
  fn: beanplot_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/beanplot_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/beanplot/beanplot_{{ version }}.tar.gz
  sha256: 49158aee3449108fd857ef43fb777f55a2b975b350a4a710788996ad19dd15ad

build:
  noarch: generic
  number: 1

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base

  run:
    - r-base

test:
  commands:
    - $R -e "library('beanplot')"  # [not win]
    - "\"%R%\" -e \"library('beanplot')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=beanplot
  license: GPL-2.0-only
  summary: Plots univariate comparison graphs, an alternative to boxplot/stripchart/violin plot.
  license_family: GPL2

  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
extra:
  recipe-maintainers:
    - conda-forge/r
    - dpryan79
    - johanneskoester
    - bgruening
    - daler
