travis:
  secure:
    BINSTAR_TOKEN: guwwWyqNzX/hZK6nYrZqpqY9JbtS3+67j3467qoC5LuaOAOA7fCiFPhF9/LIFu8JLFerIdOJs2zXu4+lYdEBweBq7Q7fXoBMSnJ/3igET1Grs/BSBceH3Id6s5FJHwEImJ1x5QqDS4AdR+w3dlqOaKF2VJcdxvKnRFEVcuFzb2QbyteYjPe1VQFchULpq1oQ8BhT9WAhrP6sZQnMtm6xrwa9g6sl1R/C/JBBy7hcHNhFX+KHfN0Hon3vZAg9H4P1kIzalPFsRAhCcndx6fLE/lemqDCKNLsdRGs1YaJTfjy6QZRGTgvO8xrAsaxDLB7sKbKWhWYEcZmdbmRoRJq3UwY9LExB9rILqhg40plXnYlByTE77pZo9H7tfhBTV60DSkAKMJU707zTFFNItbuYB+MSKCQXfY5aX9Gx3Ufvh1+Y9eY46LTuJd54mf5qNIdHyDbawprOe3v8C/BzZh45Pey75e0Qg1Mx/c1rmk3MhtJi4VKHdLBNOPCFnsaqQlqBPkdCUjcCXHcfuGewSfGamw5PL3/Ml2l3fKV7ObA51nZ9QVUtnmIOXt64+ePBguyXFZyrmLSAjXRSr8TJRrxczeFNxhq/fVb3SYo3L8tcJzbwuxhFJgzVkpgS+wq9FmS2uPskkwbR+qQ2QDyH62n9bhFFMbLDX7qZVIx8AC6LERM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
