appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: YrDjzWF2bxWzLKzo/ZUJQmyN6JU4IEF6+Obslsvwg2wQWa3w/7WQN7gzrmrMzU98P2cHN8DajFWt4b+uAcaNvZNTBOxp22mVKnhMd5UglKvt00NEumLS6lVBCgQ5foloODZWHXyfhkzV8xb1KuJMmGNBPzNTwe0SKBpCsc4NoZSEpTCGVL/JFrOPTGt7sCB+v2R4mZCDMKhihZkTzp1qhQG4u69xsP1cwV6kgt0bUux3pJr6FgaWLY2pba3uwv3X6G7VngtfNhVCPMMp3CklnIYTUq8eSsBTa0vArUC1slf44uHxS7n/cB2IfrC1B0TXnhpCm9Tpc1EIw+3m7hxvKqJ7VyWZyvLK2T7767911pMbMnHXKuHb13fQDl0AwbHpDEqrgMTbVu94L7Riu4QVkSbxko6bJaFM2P5sN8g7Olr+VW8mkJ/7c5JzsRg04Fw7Uc8NQKhz18NXRSlvHjsmMONkCwsw9oQZ/bz2FIqb+ZNllzX6Z4R7BdJrAPaWN8Dz5xIZrlsFKAEknTtwtFeXV7COe25ZJN1UzAewpJ0l3Dg+5fjl0pWMmlumt1EXeaH+nobpaKYKiFg5z/kJqsBGzAQ1sF7hFQ5p31EsiEbuw7DouY2HceQ28g+J5IrG3psPI4BortXFbr/zKU7oLJ1sca4cpXti1ckHj185GYDevtE=
